language: node_js
node_js:
- stable
branches:
  only:
  - main
cache:
  directories:
  - node_modules
install:
- yarn install
deploy:
  provider: heroku
  cleanup: false
  api_key:
    secure: GjT+/CHAxv4Ek2tmTweAYPUbQq9KPe3xbShrkixqXcGoZeDzV0ss6e1P50ISAIx0rRh4I3jJKcoSRb03oRVpEK7hRt/CbNvvya8VlP9Aj/NAvbISpdHEG6JYy3XqAZ2MnXB4YzvktB0iv3vxT11Hf0YMJb5hQY3qiwG12tgP+3AkqbcBAguIBcnohTAuYc9QS8LMyE8Ry+B2TfcQCq2erC59LRMfliq62761UgVlqir4krdtJ0YINRCSUoQ+juv0y2XbwZKHg4MMrOY4o1L64XSUI2ewVsCfQIesK6MVxkjuwXrdp+FneRJsxhqNPYt0j35nE9Y6nojDKPf81jCqYDfPHBj7ErQgN92IjYIYRcEyZeVYGkllcSxsn1Dz8cPmAiMYbADLzgYU1VGfTXg3BVwRXLJ3QojqZdx/zwwwpW3MoO23uslomuidLCmYrMGKhP1hpb8WbJ6TjTqcNcwAZJXP8yFhMJr+8+07t6KbrneHDlTiNgt4ejUr5yULkOpNzZrT8cIYchJVFWvXaoW0PRJus+y2xjw6w8BldV7Mjhsf0eQygovBIZ5V2ssyGLFRNoELOnfWhgn0y3vdxGEwVnMzE6ah6DlbQmg5pU80N2kedc8I1BQuai+uQSXJjCPlhNsFIcnhuIpMLLfrnORiPtL+CeNONMyRjuQZ1M7hqps=
  app: fixbit-app
  on:
    branch: main
