language: node_js
node_js:
  - "stable"

branches:
  only:
    - main

cache:
  directories:
    - node_modules

install:
  - yarn install

deploy:
  provider: heroku
  cleanup: false
  api_key:
    secure: $HEROKU_API_KEY
  app:
    master: fixbit-app
