language: node_js
node_js:
  - "stable"
sudo: false

branches:
  only:
    - main

cache:
  directories:
    - node_modules

install:
  - npm install

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: fixbit-app
